2020-02-21 10:53:22,205 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:53]
2020-02-21 17:01:06,795 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:02:07,412 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:05:48,964 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:06:25,326 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:07:10,526 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:08:29,251 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:12:23,670 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:14:48,348 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:17:28,153 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:18:48,015 INFO: Microblog startup [in /home/gabriel/flaskapps/megatuto/app/__init__.py:54]
2020-02-21 17:18:53,684 ERROR: Exception on /reset_password_request [POST] [in /home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gabriel/flaskapps/megatuto/app/routes.py", line 196, in reset_password_request
    send_password_reset_email(user)
  File "/home/gabriel/flaskapps/megatuto/app/email.py", line 16, in send_password_reset_email
    sender=app.config["ADMINS"][0],
NameError: name 'app' is not defined
2020-02-21 17:19:33,418 ERROR: Exception on /reset_password_request [POST] [in /home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gabriel/flaskapps/megatuto/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gabriel/flaskapps/megatuto/app/routes.py", line 196, in reset_password_request
    send_password_reset_email(user)
  File "/home/gabriel/flaskapps/megatuto/app/email.py", line 16, in send_password_reset_email
    sender=app.config["ADMINS"][0],
NameError: name 'app' is not defined
